// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FactoryGenEntity
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TemplateFileJson : TemplateFileJsonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("{\r\n  \"Id\": \"");
            
            #line 7 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.Id));
            
            #line default
            #line hidden
            this.Write("\",\r\n  \"Name\": \"");
            
            #line 8 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n  \"OriginalName\": \"");
            
            #line 9 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.OriginalName));
            
            #line default
            #line hidden
            this.Write("\",\r\n  \"NamePlural\": \"");
            
            #line 10 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.NamePlural));
            
            #line default
            #line hidden
            this.Write("\",\r\n  \"DatabaseTableName\": \"");
            
            #line 11 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.DatabaseTableName));
            
            #line default
            #line hidden
            this.Write("\",\r\n  \"Namespace\": \"");
            
            #line 12 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.Namespace));
            
            #line default
            #line hidden
            this.Write("\",\r\n  \"BaseClass\": \"");
            
            #line 13 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.BaseClass));
            
            #line default
            #line hidden
            this.Write("\",\r\n  \"PrimaryKeyType\": \"");
            
            #line 14 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.PrimaryKeyType));
            
            #line default
            #line hidden
            this.Write("\",\r\n  \"IsMultiTenant\": ");
            
            #line 15 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.IsMultiTenant.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n  \"ShouldCreateUserInterface\": ");
            
            #line 16 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.ShouldCreateUserInterface.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n  \"ShouldCreateBackend\": ");
            
            #line 17 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.ShouldCreateBackend.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n  \"ShouldAddMigration\": ");
            
            #line 18 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.ShouldAddMigration.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n  \"ShouldUpdateDatabase\": ");
            
            #line 19 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.ShouldUpdateDatabase.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n  \"CreateTests\": ");
            
            #line 20 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.CreateTests.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n  \"Properties\": [\r\n    ");
            
            #line 22 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"

     for (int i = 0; i < fileJson.Properties.Count; i++)
     {
        var pro = fileJson.Properties[i];
     
            
            #line default
            #line hidden
            this.Write("            {\r\n              \"Id\": \"");
            
            #line 28 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.Id));
            
            #line default
            #line hidden
            this.Write("\",\r\n              \"Name\": \"");
            
            #line 29 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n              \"Type\": \"");
            
            #line 30 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.Type));
            
            #line default
            #line hidden
            this.Write("\",\r\n              \"EnumType\": \"");
            
            #line 31 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.EnumType));
            
            #line default
            #line hidden
            this.Write("\",\r\n              \"EnumNamespace\": \"");
            
            #line 32 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.EnumNamespace));
            
            #line default
            #line hidden
            this.Write("\",\r\n              \"EnumAngularImport\": \"");
            
            #line 33 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.EnumAngularImport));
            
            #line default
            #line hidden
            this.Write("\",\r\n              \"IsNullable\": ");
            
            #line 34 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.IsNullable.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n              \"IsRequired\": ");
            
            #line 35 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.IsRequired.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n              \"MinLength\": ");
            
            #line 36 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.MinLength.HasValue?pro.MinLength.Value.ToString():"null"));
            
            #line default
            #line hidden
            this.Write(",\r\n              \"MaxLength\": ");
            
            #line 37 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.MaxLength.HasValue?pro.MaxLength.Value.ToString():"null"));
            
            #line default
            #line hidden
            this.Write(",\r\n              \"SortOrder\": ");
            
            #line 38 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.SortOrder.ToString()));
            
            #line default
            #line hidden
            this.Write(",\r\n              \"SortType\": ");
            
            #line 39 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.SortType.ToString()));
            
            #line default
            #line hidden
            this.Write(",\r\n              \"Regex\": \"");
            
            #line 40 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.Regex.ToString()));
            
            #line default
            #line hidden
            this.Write("\",\r\n              \"EmailValidation\": ");
            
            #line 41 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pro.EmailValidation.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n              \"EnumValues\": ");
            
            #line 42 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrEmpty(pro.EnumValues)?"null":pro.EnumValues));
            
            #line default
            #line hidden
            this.Write(",\r\n            }");
            
            #line 43 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
if(i != (fileJson.Properties.Count - 1)){
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 43 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
}
            
            #line default
            #line hidden
            this.Write("   ");
            
            #line 44 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
}
            
            #line default
            #line hidden
            this.Write("  ],\r\n  \"NavigationProperties\": [\r\n    ");
            
            #line 47 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"

     for (int i = 0; i < fileJson.navigationProperties.Count; i++)
     {
        var nav = fileJson.navigationProperties[i];
    
            
            #line default
            #line hidden
            this.Write("  \r\n        {\r\n          \"Namespace\": \"");
            
            #line 53 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.Namespace));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"EntityName\": \"");
            
            #line 54 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.EntityName));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"EntityNameWithDuplicationNumber\": \"");
            
            #line 55 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.EntityNameWithDuplicationNumber));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"EntitySetNameWithDuplicationNumber\": \"");
            
            #line 56 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.EntitySetNameWithDuplicationNumber));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"EntitySetName\": \"");
            
            #line 57 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.EntitySetName));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"DtoNamespace\": \"");
            
            #line 58 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.DtoNamespace));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"DtoEntityName\": \"");
            
            #line 59 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.DtoEntityName));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"Type\": \"");
            
            #line 60 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.Type));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"Name\": \"");
            
            #line 61 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"ReferencePropertyName\": \"");
            
            #line 62 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.ReferencePropertyName));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"DisplayProperty\": \"");
            
            #line 63 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.DisplayProperty));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"UiPickType\": \"");
            
            #line 64 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.UiPickType));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"IsRequired\": ");
            
            #line 65 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nav.IsRequired.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write("\r\n        }");
            
            #line 66 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
if(i != (fileJson.navigationProperties.Count - 1)){
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 66 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
}
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 67 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
}
            
            #line default
            #line hidden
            this.Write("  ],\r\n  \"PhysicalFileName\": \"");
            
            #line 69 "E:\14. Abp Framework\ToolSupports\GenerateEntity\GenerateEntity\Template\TemplateFileJson.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fileJson.PhysicalFileName));
            
            #line default
            #line hidden
            this.Write("\"\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class TemplateFileJsonBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
